#105-string-challenges
b00tc4mp/isdi-parttime-202406 pull request #106
Opened 2024-07-12 17:56 UTC by angelabernaldz

2024-07-23 15:38 UTC, Portaltocoding approved these changes
Por lo general todo funciona bien, faltan algunos casos inciales a tener en cuenta, y  kilos de comentarios en el código.
Keep up w the hard work! 🍰 🍰 🚀

2024-07-23 15:38 UTC, Portaltocoding commented on staff/angela-bernaldez/string-standalone/repeat.js
puntos extra por usar ``` throw new Error``` 🍰 🍰

2024-07-23 15:38 UTC, Portaltocoding commented on staff/angela-bernaldez/string-standalone/split.js
tarjeta amarilla por usar un método 🟨

2024-07-23 15:38 UTC, Portaltocoding commented on staff/angela-bernaldez/string-standalone/trim.js
console asserts

2024-07-23 17:12 UTC, angelabernaldz commented on staff/angela-bernaldez/string-standalone/split.js
no me habia dado ni cuenta! gracias! 💯

2024-07-23 17:13 UTC, angelabernaldz commented on staff/angela-bernaldez/string-standalone/trim.js
te refieres a que me estaria bien incluir alguno mas o que fallan los que estan?

2024-07-29 15:33 UTC, rucev requested changes
Revisa en el file trim.js esas llamadas raras a toUpperCase en los asserts y ya estará listo para mergear 🦆

2024-07-29 15:33 UTC, rucev commented on staff/angela-bernaldez/string-standalone/trim.js
> +const result1 = toUpperCase(" hello wooooorld     ");
Estas llamando a las funciones toUpperCase en lugar de a la función trim en los asserts, el resto esta perfecto

2024-07-29 17:12 UTC, angelabernaldz commented on staff/angela-bernaldez/string-standalone/trim.js
> +const result1 = toUpperCase(" hello wooooorld     ");
revisado! :) muchas gracias

2024-07-31 10:45 UTC, rucev approved these changes

2024-07-31 10:45 UTC, merged