#102-string-stand-alone
b00tc4mp/isdi-parttime-202406 pull request #108
Opened 2024-07-13 12:21 UTC by CRBM84

Submitting files for three challenges with a local implementation of the string methods on MND

2024-07-29 15:38 UTC, rucev commented
cambia el nombre de la pr a #102-string-standalone para que siga el mismo formato que el resto

2024-08-07 10:06 UTC, rucev requested changes
Si añades el indexOf y limpias ese console.log ya tienes lo mínimo para mergear!

2024-08-07 10:06 UTC, rucev commented on staff/carlos-bock/string-challenges/slice.js
> +console.log(slice(string1,indexOne,indexTwo));
Este console.log de debuggeo/testeo sobra

2024-08-07 16:53 UTC, CRBM84 commented on staff/carlos-bock/string-challenges/slice.js
> +console.log(slice(string1,indexOne,indexTwo));
Gracias lo he quitado.

2024-08-10 11:25 UTC, rucev approved these changes

2024-08-10 11:26 UTC, merged