#107-string-standalone
b00tc4mp/isdi-parttime-202406 pull request #109
Opened 2024-07-14 12:07 UTC by CarlosLemonCode

2024-07-29 09:58 UTC, angelabernaldz reviewed
En el ejercicio de toUpperCase me da error al correr el codigo ya que en el TDD llamas a la funcion toUpperCase pero la funcion que has creado se llama toLowerCase - pienso que te has olvidado de cambiarle el nombre ya que habias creado primero toLowerCase y checkeando el codigo, la funcion hace lo que toUpperCase deberia

2024-07-29 10:00 UTC, angelabernaldz reviewed
El metodo de trimStart creo que no era necesario - no estaba en la lista de Ventu - pero muy bien por incluirlo! trabajando duro 👍

2024-07-29 10:04 UTC, angelabernaldz reviewed
Muy interesante la forma que has encontrado de comparar arrays utilizando JSON.stringfy(array)!

2024-07-29 10:09 UTC, angelabernaldz requested changes
Muy bien en general! Me gusta que hayas añadido comentarios explicando el código.

Le doy a solicitar cambios para que revises la funcion toUpperCase como te puse en otro comentario y una vez no de error, te doy el visto bueno! 🥇

2024-08-03 15:39 UTC, CarlosLemonCode commented
> En el ejercicio de toUpperCase me da error al correr el codigo ya que en el TDD llamas a la funcion toUpperCase pero la funcion que has creado se llama toLowerCase - pienso que te has olvidado de cambiarle el nombre ya que habias creado primero toLowerCase y checkeando el codigo, la funcion hace lo que toUpperCase deberia

Corregido! Gracias por la ayuda 😄 !!

2024-08-03 15:39 UTC, CarlosLemonCode commented
> Muy bien en general! Me gusta que hayas añadido comentarios explicando el código.
> 
> Le doy a solicitar cambios para que revises la funcion toUpperCase como te puse en otro comentario y una vez no de error, te doy el visto bueno! 🥇

Listo! :)

2024-08-04 19:26 UTC, Rafa0297 commented on staff/carlos-fernandez/string-standalone/includes.2.js
> +  debugger
Eliminar el debugger de esta linea

2024-08-04 19:28 UTC, Rafa0297 commented on staff/carlos-fernandez/string-standalone/replace.js
> +console.log(result); // "Hola que mal"
Eliminar el ejemplo de uso (Variable y console.log)

2024-08-04 19:30 UTC, Rafa0297 commented on staff/carlos-fernandez/string-standalone/slice.js
> +            newString.push(input[i]);
no esta permitido usar el metodo push

2024-08-04 19:33 UTC, Rafa0297 commented on staff/carlos-fernandez/string-standalone/split.js
> +            newArray.push(newString);
cambiar el metodo push por newArray[newArray.length] = newString

2024-08-04 19:33 UTC, Rafa0297 commented on staff/carlos-fernandez/string-standalone/split.js
> +    newArray.push(newString);
Cambiar esta el push en esta linea

2024-08-04 19:41 UTC, Rafa0297 requested changes
Hola, he visto que habria que realizar algunos cambios en el código:
1)  Eliminar el debugger en el método includes.
2)  Eliminar el ejemplo de uso y console.log() en el método replace.
3)  Utilizar otro método que no sea el push en el metodo slice y en el método Split.


Nota: Preguntar a Flors si en el metodo concat se puede usar el spread operator en los argumentos, no estoy seguro si se ouede porque se genera un array de argumentos.

2024-08-08 15:20 UTC, CarlosLemonCode commented
> Hola, he visto que habria que realizar algunos cambios en el código:
> 
> 1. Eliminar el debugger en el método includes.
> 2. Eliminar el ejemplo de uso y console.log() en el método replace.
> 3. Utilizar otro método que no sea el push en el metodo slice y en el método Split.
> 
> Nota: Preguntar a Flors si en el metodo concat se puede usar el spread operator en los argumentos, no estoy seguro si se ouede porque se genera un array de argumentos.

Cambios realizados! Le pregunto a Flors, por el resto he corregido lo que me has pedido 🚀

2024-08-12 10:40 UTC, CarlosLemonCode commented on staff/carlos-fernandez/string-standalone/includes.2.js
> +  debugger
Hecho!

2024-08-12 10:40 UTC, CarlosLemonCode commented on staff/carlos-fernandez/string-standalone/replace.js
> +console.log(result); // "Hola que mal"
Hecho!

2024-08-12 10:40 UTC, CarlosLemonCode commented on staff/carlos-fernandez/string-standalone/slice.js
> +            newString.push(input[i]);
Corregido

2024-08-12 10:40 UTC, CarlosLemonCode commented on staff/carlos-fernandez/string-standalone/split.js
> +            newArray.push(newString);
Corregido! Gracias por el consejo

2024-08-12 10:40 UTC, CarlosLemonCode commented on staff/carlos-fernandez/string-standalone/split.js
> +    newArray.push(newString);
Corregido

2024-08-12 13:03 UTC, Rafa0297 approved these changes
Correcto! Funciona bien el codigo :+1:

2024-08-16 09:13 UTC, rucev approved these changes
🍋 👍

2024-08-16 09:13 UTC, merged