#112- string-standalone
b00tc4mp/isdi-parttime-202406 pull request #113
Opened 2024-07-15 16:32 UTC by LeideVanessaC

**Metodos Strings**

2024-07-15 17:48 UTC, venturars commented
El título tiene un espacio detrás del primer -

2024-07-16 17:08 UTC, LeideVanessaC commented
> El título tiene un espacio detrás del primer -
arreglado

2024-08-04 21:33 UTC, CarlosLemonCode commented on staff/vanessa-cardoso/string-standalone/concat.js
> +console.assert(result1 === "Buenos".concat("dia!"), {result: result1, message: "Test 1 No pasado."});
Fíjate que el assert está incompleto. Te falta incluir el espacio en blanco para que se compare igual que la función concat.

2024-08-04 21:34 UTC, CarlosLemonCode commented on staff/vanessa-cardoso/string-standalone/concat.js
> +console.assert(result3 === "Tenho".concat(  "2 ", "hermanas"), {result: result3, message: "Test 3 No pasado."});
Este assert también está incompleto por el mismo motivo que el anterior.

2024-08-04 21:38 UTC, CarlosLemonCode commented on staff/vanessa-cardoso/string-standalone/to-lower-case.js
> +let string = "A CASA";
Me da error al declarar esta variable. Creo que si la eliminas el código funcionaría bien.

2024-08-04 21:39 UTC, CarlosLemonCode requested changes
Hay alguna cosita para revisar 😄  por el resto buen trabajo 🚀

2024-10-14 17:10 UTC, closed without merging