#111-string-standalone
b00tc4mp/isdi-parttime-202406 pull request #114
Opened 2024-07-16 15:52 UTC by Portaltocoding

Estoy teniendo problemas con el guardado de los archivos en mi local; los archivos serán correctamente subidos en las proximas PRs

2024-07-24 16:55 UTC, CRBM84 commented on staff/carlos-portal/string-standAlone/trim.js
> +            llena += string[i];
Aquí el código se come los espacios entre palabras, hay que añadir otra condición. Me ha pasado lo mismo.

2024-07-24 16:58 UTC, CRBM84 commented on staff/carlos-portal/string-standAlone/slice.js
> +function slicing (str,firstIndex,lastIndex){
Creo que el método de slice permite cero parámetros, un índice o dos índices. El código marcha bien, pero creo que algunos casos son más complejos. Yo resolví esto pasando parámetros de (string, ... indice). :)

2024-07-24 16:58 UTC, CRBM84 commented on staff/carlos-portal/string-standAlone/to-lower-case.js
> +let mayusculas = "ABCDEFGHIJKLMNOPQRSTUVWXYZÇÑ"
Cambiar a const de cara al futuro.

2024-07-29 15:58 UTC, rucev commented on staff/carlos-portal/string-standAlone/concat.js
> +console.log(concatenar("palabra", "otra", "otrgkmd", "lsdjgnfds"));
este console.log no hace falta y se puede limpiaotrgkmd

2024-07-29 16:04 UTC, rucev commented on staff/carlos-portal/string-standAlone/ends-with.js
> +let result1 = termina('console log', 'log');
En los asserts estas pasandole la funcion string.termina() en lugar de string.endsWith() y da fallo

2024-07-29 16:13 UTC, rucev commented on staff/carlos-portal/string-standAlone/indexof.js
> +let indice = -1 // menos 1 porque y si esta en posición 0?
Borra las variables del principio del indexOf que si no salta fallo de "indice has already been declared"

2024-07-29 16:18 UTC, rucev commented on staff/carlos-portal/string-standAlone/split01.js
> +
falta algún assert en el split (y no sé hasta que punto es legal en este challenge usar push al ser un método de array)

2024-07-29 16:20 UTC, rucev commented on staff/carlos-portal/string-standAlone/starts-with.js
> +console.assert(result1 === 'console log'.empieza('log'), { result: result1, message: 'Test 1 no pasado' });
te ha pasado lo mismo que al hacer el endsWith con los asserts del empieza, salta error de "console log".empieza is not a function"

2024-07-29 16:29 UTC, rucev commented on staff/carlos-portal/string-standAlone/to-lower-case.js
> +let mayusculas = "ABCDEFGHIJKLMNOPQRSTUVWXYZÇÑ"
Además, si vas a usar estas variables que declaras al inicio únicamente dentro de la función en sí es también buena opción meterlas dentro de la función y no fuera

2024-07-29 16:29 UTC, rucev requested changes
Hay que hacer un par de cambios en algunos archivos donde fallan los asserts pero en general esta genial!

2024-08-21 08:18 UTC, rucev approved these changes
👍

2024-08-21 08:19 UTC, merged