#110-string-standalone
b00tc4mp/isdi-parttime-202406 pull request #138
Opened 2024-07-20 12:31 UTC by itsmePo

Creating a series of string methods for testing and notes purposes.

2024-07-22 18:03 UTC, Portaltocoding approved these changes
Por lo general muy buen código, todo muy limpio 👍 
me faltan comentarios explicandome que pasa
no te pido cambios porque creo que estos son mínimos y no hace falta enrollarse! 
Ánimo con ese trabajazo! 🍰 🍰

2024-07-22 18:03 UTC, Portaltocoding commented on staff/borja-garcia/string-standalone/concat.js
No puedes usar otros métodos!

2024-07-22 18:03 UTC, Portaltocoding commented on staff/borja-garcia/string-standalone/includes.js
console.log(includes("jaskhasdb","hasel")) me da true

2024-07-22 18:03 UTC, Portaltocoding commented on staff/borja-garcia/string-standalone/split.js
🍰 muy guay el codigo  y muy bien explicado 🗡️ 🍰  pero le falta un detalle de la propia documentación de split, cadena.split([separador][,limite]) 
[limite]

    Opcional. Entero que especifica un límite sobre el número de divisiones a realizar. El método split() todavía se divide en todas las concordancias del separador, pero divide la matriz devuelta en la cantidad de elementos impuesta por el limite.

2024-07-22 18:03 UTC, Portaltocoding commented on staff/borja-garcia/string-standalone/slice.js
creo que este código es super válido pero también lo veo complejo en demasía, creo que con el bucle for ya lo tenías 🍰 🍰 
si no estuviera tan dormido no te pediría algun comentario para no tener que leer cada if

2024-07-29 10:25 UTC, angelabernaldz requested changes
Revisa los ejercicios cuando puedas e intenta cambiar aquellos fallos que causan errores y tambien aquellos en los que utilizas metodos intrinsecos, porfa.

El resto son sugerencias, a ver que opina el resto. Muy buen codigo y explicados los ejercicios! 👍 💯

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/concat.js
mismo comentario! no deberias usar el metodo join de strings! trata de buscar otra forma

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/endsWith.js
de nuevo no podrias usar: word.toString() ya que estarias utilizando un metodo intrinseco de string y hemos dicho que no se puede usar otros metodos!

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/includes.js
me da que el Test 4 no pasa. Revisalo de nuevo, porfa

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/indexOf.js
me da el error: string.subString is not a function.
Anyway no podrias utilizar el metodo string.subString si existe, ya que estarias utilizando un metodo intrinseco de strings y hemos dicho que no se puede!

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/slice.js
Pienso que se podria simplificar un poco la parte inicial en la que checkeas las excepciones!

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/toUpperCase.js
me da error ya que en el TDD en el caso 2 llamas a convertirMayusAMinus en lugar de convertirMinusAMayus.

Otra cosa es que nombre le has dado a la funcion, creo que deberiamos llamarle como el metodo intrinseco de string que intentamos recrear. En este caso, yo la llamaria: toUpperCase

2024-07-29 10:25 UTC, angelabernaldz commented on staff/borja-garcia/string-standalone/toLowerCase.js
Lo mismo que te decia en el metodo de minusculas a mayusculas! yo les llamaria de la misma forma que el metodo original intrinseco de strings, en este caso: toLowerCase

2024-08-02 09:27 UTC, rucev requested changes

2024-08-02 09:27 UTC, rucev commented on staff/borja-garcia/string-standalone/at.js
> +console.assert(reslt1 === 'Hello'.at(2), {
Falla el assert al poner "reslt1" en lugar de "result1"

2024-08-02 09:27 UTC, rucev commented on staff/borja-garcia/string-standalone/includes.js
> +        if (characterOfString === searchString[0]) result = true;
Estás comparando con el primer elemento de searchString cuando a veces esta tiene un length superior a 1. Al plantearlo así das falsos positivos como el que comenta Portal: 
```
includes("jaskhasdb","hasel") === true
```

Porque solo compruebas que haya una "h" (`"hasel"[0]`) en el string original. Deberías comprobar si están todos los caracteres del searchString y si están en el mismo orden.

2024-08-02 09:27 UTC, rucev commented on staff/borja-garcia/string-standalone/indexOf.js
> +const result1 ? indexOf('hello', 'll');
A parte de la corrección que ya te ha mencionado Angela, también hay que cambiar el '?' de result1 por un '='

2024-08-07 14:42 UTC, rucev requested changes
Falta reubicar el pixel art y revisar el concat, pero todo lo demás esta genial

![chef-kiss](https://i.pinimg.com/originals/a7/03/1e/a7031e8ce4a66c2aaafd87aca298290a.gif)

2024-08-07 14:42 UTC, rucev commented on staff/borja-garcia/playground/pixel-art/pixel-art.html
¿el pixel art en esta pr? Debería estar en la suya propia, se merece ser el protagonista de su propio issue y su propia pull request!

2024-08-07 14:42 UTC, rucev commented on staff/borja-garcia/string-standalone/concat.js
> +  for (let i = 0; i < str1.length; i++) {
`Uncaught ReferenceError: str1 is not defined`

Si te refieres al primer string de los argumentos strings seria string[0] y si te refieres a la longitud del array con todos los argumentos (o strings) sería strings.length

2024-08-10 11:29 UTC, rucev approved these changes

2024-08-10 11:29 UTC, merged