#174-pixel-art
b00tc4mp/isdi-parttime-202406 pull request #175
Opened 2024-07-31 12:16 UTC by CRBM84

2024-08-03 14:57 UTC, Rafa0297 requested changes
Hola. Por lo visto tienes un archivo save.md que no forma parte de la estructura del ejercicio, luego te faltaria crear la pipeline para alojar tu pixel-art con surge como lo ha enseñado Flors en clase. Saludos.

2024-08-13 13:16 UTC, CRBM84 commented
> Hola. Por lo visto tienes un archivo save.md que no forma parte de la estructura del ejercicio, luego te faltaria crear la pipeline para alojar tu pixel-art con surge como lo ha enseñado Flors en clase. Saludos.

Gracias he añadido los git actions de surge :)

2024-09-04 10:24 UTC, CRBM84 commented
https://mario85-pixelart.surge.sh/

2024-09-04 10:25 UTC, CarlosLemonCode approved these changes
Coool!!! 🍋🍋🍋🍋🍋

2024-10-14 17:12 UTC, closed without merging