#97-string-standalone
b00tc4mp/isdi-parttime-202406 pull request #178
Opened 2024-08-02 17:49 UTC by Rodrigoregomedeiros

String standalone

2024-08-07 15:07 UTC, rucev requested changes
El código esta genial, excepto ese result8 que rompe un assert, cambialo y esta para mergear.

Y lo de los debuggers puedo pasarlo por alto *(solo esta vez)*...

Pero de cara al futuro piensa que cuando se mergea una pull request la idea es que el proyecto esta listo para que lo usen los usuarios. Imagina que entras a instagram y salta el debugger de la nada! Raro, y muy incomodo para cualquier usuario.

Por eso os pido que os acostumbréis a limpiar todo lo relativo a debuggeo de cara a la pull request (ya sea el comando `debugger` en sí o posibles console.logs).

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/endsWith.js
> +console.log(result1, result2, result3, result4);
Se te ha colado un console.log de debuggeo! Si quieres dejar un console.log para asegurarte que el código se ha ejecutado y no han fallado los tests, deja un mensaje tipo:
```js
console.log('tests superados')
```

Si no la consola se llena de "ruido" difícil de identificar y cuando reviso código me quedo "true true false ¿qué? ¿y por qué?"

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/indexOf.js
> +      result: result8,
`Uncaught ReferenceError: result8 is not defined`

Sospecho que ahí debería ir result6 🧐

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/repeat.js
> +debugger
Como norma general, intenta no tener debuggers perdidos en el código final de la PR

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/replace.js
> +debugger
¡ya van dos! ✌️

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/slice.js
> +debugger
Tercer debugger 🥉 que no debería estar ahí

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/startsWith.js
> +debugger
debugger nº 4, me estoy quedando sin ideas para emojis

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/toLowerCase.js
> +debugger
Debugger que no hace falta por aquí también

2024-08-07 15:07 UTC, rucev commented on staff/rodrigo-medeiros/string-standalone/toUpperCase.js
> +debugger;
Otro!

2024-08-14 22:40 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/endsWith.js
> +console.log(result1, result2, result3, result4);
Gracias por el feedback! he quitado el console log del codigo y revisado.

2024-08-15 00:12 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/indexOf.js
> +      result: result8,
Codigo arreglado.

2024-08-15 00:15 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/repeat.js
> +debugger
Debugger quitado.

2024-08-15 00:16 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/replace.js
> +debugger
Debugger quitado.

2024-08-15 00:32 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/slice.js
> +debugger
Quitting debugger

2024-08-15 14:03 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/startsWith.js
> +debugger
Debugger quitado.

2024-08-15 14:05 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/toLowerCase.js
> +debugger
quitting debugger

2024-08-15 14:08 UTC, Rodrigoregomedeiros commented on staff/rodrigo-medeiros/string-standalone/toUpperCase.js
> +debugger;
debugger quitado.

2024-08-16 09:32 UTC, rucev approved these changes

2024-08-16 09:33 UTC, merged