#192-prototype
b00tc4mp/isdi-parttime-202406 pull request #193
Opened 2024-08-22 18:23 UTC by CarlosLemonCode

2024-10-21 11:37 UTC, rucev requested changes
**Cambios en la carpeta de biblio:**

- ¿Hay algún motivo para que el file de **copy-within** este en mayúscula? Igualmente, si lo vas a dejar así deberías cambiar el import del index para que coincida (aunque te recomiendo **cambiar el nombre a minúscula** para que coincida con todos los otros archivos).

- Te falta añadir los **tests del constructor al index de test** (los tienes hechos y los pasa sin problemas, pero deberían estar en el index para que se testee automático también).

- En varios **tests en que usas chai assert** que no son los del método "at" (en el "reduce", por ejemplo) se te ha colado el **mensaje de fallo** de "The at method from Biblio does not work as the Array at method." Y en el shift tienes un "The reduce method from Biblio does not work as the Array at method.". Tus mensajes de fallo en los tests tienen una crisis de identidad

El resto esta ya para mergeear.

> ¿A quién no le va a gustar un slice en chain characters?

![](https://c.tenor.com/sG4QeAFtXTYAAAAC/tenor.gif)

2024-10-23 13:26 UTC, rucev commented
Los dos últimos mensajes en el flow de la pr son porque ha habido un pequeño despiste con el número de issue en un commit de la rama 194 de Angela. Ignorad el "mentioned this pull request" y el "pushed a commit that referenced this pull request"

2024-10-24 10:22 UTC, CarlosLemonCode commented
> **Cambios en la carpeta de biblio:**
> 
> * ¿Hay algún motivo para que el file de **copy-within** este en mayúscula? Igualmente, si lo vas a dejar así deberías cambiar el import del index para que coincida (aunque te recomiendo **cambiar el nombre a minúscula** para que coincida con todos los otros archivos).

Arreglado! Lo tenía en mayúsculas para identificar cuál me faltaba por acabar.

> * Te falta añadir los **tests del constructor al index de test** (los tienes hechos y los pasa sin problemas, pero deberían estar en el index para que se testee automático también).

Arreglado! 

> * En varios **tests en que usas chai assert** que no son los del método "at" (en el "reduce", por ejemplo) se te ha colado el **mensaje de fallo** de "The at method from Biblio does not work as the Array at method." Y en el shift tienes un "The reduce method from Biblio does not work as the Array at method.". Tus mensajes de fallo en los tests tienen una crisis de identidad

Cierto! Menuda ensalada de métodos he hecho ahí... Ya está arreglado.

> 
> El resto esta ya para mergeear.
> 
> > ¿A quién no le va a gustar un slice en chain characters?
> 
> ![](https://camo.githubusercontent.com/4b06ae6f004a5f748ff2531ec4a88025b7637ed979d7eec64d7096b6371ff082/68747470733a2f2f632e74656e6f722e636f6d2f734734516541467458545941414141432f74656e6f722e676966) [ ![68747470733a2f2f632e74656e6f722e636f6d2f734734516541467458545941414141432f74656e6f722e676966](https://camo.githubusercontent.com/4b06ae6f004a5f748ff2531ec4a88025b7637ed979d7eec64d7096b6371ff082/68747470733a2f2f632e74656e6f722e636f6d2f734734516541467458545941414141432f74656e6f722e676966) ](https://camo.githubusercontent.com/4b06ae6f004a5f748ff2531ec4a88025b7637ed979d7eec64d7096b6371ff082/68747470733a2f2f632e74656e6f722e636f6d2f734734516541467458545941414141432f74656e6f722e676966) [ ](https://camo.githubusercontent.com/4b06ae6f004a5f748ff2531ec4a88025b7637ed979d7eec64d7096b6371ff082/68747470733a2f2f632e74656e6f722e636f6d2f734734516541467458545941414141432f74656e6f722e676966)

2024-10-24 11:19 UTC, rucev approved these changes

2024-10-24 11:20 UTC, merged