#32- my-class-notes
b00tc4mp/isdi-parttime-202406 pull request #34
Opened 2024-07-03 14:36 UTC by LeideVanessaC

2024-07-04 18:49 UTC, Portaltocoding approved these changes
Hay espacios en los títulos de la PR, lo demás todo guay!

2024-07-08 08:55 UTC, LeideVanessaC commented
> Hay espacios en los títulos de la PR, lo demás todo guay!

Titulo corregido!

2024-07-15 17:28 UTC, venturars requested changes
El archivo 'staff/vanessa-cardoso/.gitignore' no debería existir. Ahora miso está borrado el contenido pero el archivo está trackeado vacío.

2024-07-17 10:13 UTC, rucev approved these changes
👍

2024-07-17 17:52 UTC, venturars approved these changes

2024-07-18 17:05 UTC, Portaltocoding approved these changes

2024-07-22 09:43 UTC, merged