#48 challenge counting letters
b00tc4mp/isdi-parttime-202406 pull request #49
Opened 2024-07-04 05:54 UTC by CRBM84

This is a pull request for the counting letters challenge. I thinks I figured out the pull request issue.

2024-07-04 08:34 UTC, itsmePo commented
¡Holi!
El código, la branch y demás está bien, pero me salta error con tu .gitignore.
Con un par de consultas rápidas al señor GPT me sale que tienes código en el archivo que está en conflicto con la propia branch.
Habría que solucionar eso antes de continuar!

Te dejo un enlace con los pasos a seguir junto al señor GPT. 
https://chatgpt.com/share/86cf2cbb-a6c1-4cf0-8332-c734d19923ef

2024-07-04 08:35 UTC, itsmePo requested changes
Pese a que sale todo correcto y el código funciona, tu archivo .gitignore está en conflicto con la rama.
En uno de los comentarios te he dejado un enlace paso a paso para poder solucionarlo! :D

2024-07-04 09:43 UTC, Rafa0297 requested changes
Faltaría agregar la condición en la linea 19 para que funcione bien el console.assert()

2024-07-04 09:43 UTC, Rafa0297 commented on staff/carlos-bock/challenge-letter/counting-letters.js
> +  console.assert(typeof result3 === "number", {
En esta linea la condicion siempre seria `true` porque `typeof result3` siempre sera `number`. Para solucionarlo debes agregarle la condicion `result3 === 3`

2024-07-05 05:51 UTC, CRBM84 commented on staff/carlos-bock/challenge-letter/counting-letters.js
> +  console.assert(typeof result3 === "number", {
@Rafa0297  creo que ese era el código original, ¿no? No lo quería tocar por si acaso. ¿Saca un error el código? :/

2024-07-05 05:54 UTC, CRBM84 commented
> ¡Holi! El código, la branch y demás está bien, pero me salta error con tu .gitignore. Con un par de consultas rápidas al señor GPT me sale que tienes código en el archivo que está en conflicto con la propia branch. Habría que solucionar eso antes de continuar!
> 
> Te dejo un enlace con los pasos a seguir junto al señor GPT. https://chatgpt.com/share/86cf2cbb-a6c1-4cf0-8332-c734d19923ef

@itsmePo  gracias! Lo voy a ver :) ¿Que clase de error ha salido? :/ 

Gracias por el enlace lo trato de solucionar.

2024-07-06 13:36 UTC, CRBM84 commented
> ¡Holi! El código, la branch y demás está bien, pero me salta error con tu .gitignore. Con un par de consultas rápidas al señor GPT me sale que tienes código en el archivo que está en conflicto con la propia branch. Habría que solucionar eso antes de continuar!
> 
> Te dejo un enlace con los pasos a seguir junto al señor GPT. https://chatgpt.com/share/86cf2cbb-a6c1-4cf0-8332-c734d19923ef

Se ha resuelto el problema. :)

2024-07-06 13:36 UTC, CRBM84 commented on staff/carlos-bock/challenge-letter/counting-letters.js
> +  console.assert(typeof result3 === "number", {
Ya esta :)

2024-07-08 16:37 UTC, Rafa0297 requested changes
Hay que cambiar el nombre de la carpeta /challenge-letters a /challenges

2024-07-08 16:37 UTC, Rafa0297 commented on staff/carlos-bock/challenge-letter/counting-letters.js
> +  console.assert(typeof result3 === "number", {
El codigo va bien, lo que he visto es que el nombre de la carpeta no es correcto, deberia ser `staff/carlos-bock/challenges/counting-letters.js`

2024-07-15 17:53 UTC, venturars commented
Esta PR tiene conflictos de merging

2024-07-19 09:26 UTC, CarlosLemonCode approved these changes

2024-07-19 09:29 UTC, rucev commented
Elimina el console.log dentro de la función

2024-07-19 09:31 UTC, CRBM84 reviewed
Extra console.log removed.

2024-07-19 09:32 UTC, rucev approved these changes
😄

2024-07-19 09:32 UTC, merged