#52-create-class-notes
b00tc4mp/isdi-parttime-202406 pull request #53
Opened 2024-07-04 10:20 UTC by itsmePo

2024-07-04 18:20 UTC, Carlos00004 approved these changes
Grande Borja, todo en orden.

2024-07-05 05:35 UTC, CRBM84 approved these changes

2024-07-07 13:01 UTC, Rafa0297 approved these changes
Chapeau!

2024-07-09 17:34 UTC, venturars requested changes
El archivo 'staff/borja-garcia/.gitignore' no debería estar en esta PR

2024-07-10 16:47 UTC, Rafa0297 approved these changes

2024-07-10 17:32 UTC, venturars approved these changes

2024-07-10 17:32 UTC, merged