27 challenge binary to decimal
b00tc4mp/isdi-parttime-202406 pull request #62
Opened 2024-07-05 05:45 UTC by CRBM84

Updated file with alternate solution. Fixed git issue. PR new file.

2024-07-07 14:59 UTC, Portaltocoding approved these changes
code works, remember to submit the solutions under the style guidelines that we set. 🍸 👍

2024-07-08 09:11 UTC, LeideVanessaC commented
Tienes que corregir el titulo, acordamos de colocar guion entre las palabras.
El código estas funcionando bien 👍

2024-07-08 09:12 UTC, LeideVanessaC approved these changes

2024-07-08 18:11 UTC, venturars requested changes
El archivo 'staff/carlos-bock/.gitignore' no debería existir en esta PR

2024-07-10 17:37 UTC, CRBM84 commented
Connect to issue 27 challenge binary to decimal #62 
Manually created branches.

2024-07-11 19:52 UTC, venturars commented
Esta PR no sigue la nomemclatura establecida

2024-07-14 11:07 UTC, LeideVanessaC approved these changes

2024-07-15 17:49 UTC, venturars approved these changes

2024-07-15 17:49 UTC, merged