#66-challenge-is-even
b00tc4mp/isdi-parttime-202406 pull request #68
Opened 2024-07-07 09:15 UTC by CRBM84

2024-07-07 19:47 UTC, Rafa0297 requested changes
Hola Carlos, debes tener en cuenta que los espacios tambien influyen en el parámetro de la función, si llamas a la funcion de esta manera `isEven('ho la')` te daría 5 y no 4 que es el resultado que esperamos.

 Puedes resolverlo con un ciclo For o usando Regex con el metodo .replace().

2024-07-08 18:12 UTC, venturars requested changes
Esta PR tiene archivos que no son de la misma

2024-07-09 17:58 UTC, Rodrigoregomedeiros approved these changes
Codigo funciona bien!

2024-07-09 18:03 UTC, Rafa0297 requested changes
Recomiendo cambiar el codigo de acuerdo a como estaba escrito en la issue

2024-07-18 15:35 UTC, angelabernaldz commented
Hola Carlos! Acabo de revisar el código y funciona, no da ningún error. Pero sí creo que podrían mejorarse algunas cosas:

- Has utilizado varios return dentro de la function para retornar el mismo parámetro (result). Yo guardaría el valor que quieras en result en cada caso y haría un único return al final de la función.
- Como estamos haciendo TDD, el primer if statement que colocas en la función no sería necesario. No hay ningún caso que queramos comprobar en el que le pasemos a la función algo que no sea number o string.
- Lo ultimo y esto es un comentario personal, igual la habria hecho un poco mas simples sin poner otro condicional if dentro del caso de number o string, ya que la expresión: value % 2 === 0 directamente te da un true o false, con lo cual podrías devolver eso

2024-07-18 15:36 UTC, angelabernaldz reviewed
Te pongo un comentario de momento y a ver que opinas tu y opina el resto antes de que la apruebe :)

2024-07-19 09:45 UTC, CRBM84 commented
> Te pongo un comentario de momento y a ver que opinas tu y opina el resto antes de que la apruebe :)

Gracias he simplificado el cogido :)

2024-07-22 10:56 UTC, rucev approved these changes

2024-07-22 14:45 UTC, venturars approved these changes

2024-07-22 15:26 UTC, merged