#71-is-even-challenge
b00tc4mp/isdi-parttime-202406 pull request #72
Opened 2024-07-07 12:32 UTC by Rafa0297

2024-07-07 13:20 UTC, CRBM84 approved these changes
👍🏼

2024-07-07 17:19 UTC, Carlos00004 commented
Actualmente considera los espacios un carácter también. Para eliminarlos te aconsejo la función .replace( ). Así no te los tendrá en cuenta y sólo evaluará el num de carácteres.

2024-07-07 17:28 UTC, Carlos00004 requested changes
Échale un ojo al .replace ( ). Buen trabajo!

2024-07-07 19:19 UTC, Rafa0297 commented
Gracias por tu recomendación! @Carlos00004 

He cambiado el código considerando los espacios en los strings, en este caso he utilizado un ciclo For. He añadido los test correspondientes.

2024-07-08 15:46 UTC, Carlos00004 commented
> Gracias por tu recomendación! @Carlos00004
> 
> He cambiado el código considerando los espacios en los strings, en este caso he utilizado un ciclo For. He añadido los test correspondientes.

Genial! 👍

2024-07-08 15:47 UTC, Carlos00004 approved these changes

2024-07-08 18:08 UTC, venturars approved these changes

2024-07-08 18:08 UTC, merged

2024-07-08 18:08 UTC, CRBM84 approved these changes