#81-challenge-is-even
b00tc4mp/isdi-parttime-202406 pull request #82
Opened 2024-07-08 16:26 UTC by LeideVanessaC

debugging

2024-07-08 16:55 UTC, Rafa0297 requested changes
Hay que revisar los codigos de los dos challenges. Recomiendo guardar los dos challenges en una sola carpeta que se llame `staff/vanessa-cardoso/challenges`

2024-07-08 16:55 UTC, Rafa0297 commented on staff/vanessa-cardoso/challenge-letter/counting-letters.js
> +console.asset(typeof result3 === 'number', {result: result3, message: 'test 3 no pasado'})
Me da un error al ejecutar. Tienes un error de tipeo en el console.assert() de la linea 19.

2024-07-08 16:55 UTC, Rafa0297 commented on staff/vanessa-cardoso/challenge-is-even/challenge-is-even.js
> +function isEven(value) {
Los test no pasan. Debes revisar la funcion para que puedan pasar.

2024-07-09 12:48 UTC, LeideVanessaC commented
> Hay que revisar los codigos de los dos challenges. Recomiendo guardar los dos challenges en una sola carpeta que se llame `staff/vanessa-cardoso/challenges`

los codigos ya están en la misma carpeta challenges, como recomiendado!👍

2024-07-09 15:40 UTC, Carlos00004 requested changes
El archivo [staff/vanessa-cardoso/challenges/counting-letters.js] pertenece a otra PR

2024-07-09 15:42 UTC, Carlos00004 commented
El código me funciona 👍

2024-07-09 16:54 UTC, Rafa0297 commented
Como ha mencionado @CarlosLemonCode El archivo `staff/vanessa-cardoso/challenges/counting-letters.js` debes eliminarlo porque no es parte de esta PR

2024-07-09 16:55 UTC, Rafa0297 commented
El codigo del archivo `staff/vanessa-cardoso/challenges/challenge-is-even.js` funciona correctamente

2024-07-10 05:37 UTC, CRBM84 approved these changes

2024-07-10 05:38 UTC, CRBM84 requested changes
Se han metido dos archivos, borra el que no se necesita por fa, el otro esta bien :)

2024-07-10 12:53 UTC, LeideVanessaC commented
Ya lo borre el archivo que estaba como extra (counting letters).

2024-07-10 13:02 UTC, Rafa0297 approved these changes
Todo bien 👍

2024-07-10 13:16 UTC, LeideVanessaC commented
*Cuando crie la rama la hice partiendo de la del issue #75, por eso sale en el historial de commits el issue #75.
No pude arreglarlo porque solo sé hacerlo con un comando que Ventu nos ha prohibido usar (git rebase). 
Así que por ahora lo dejo así.*

2024-07-11 16:04 UTC, CarlosLemonCode reviewed
Lo veo bien 👍 !

2024-07-11 16:04 UTC, CarlosLemonCode approved these changes

2024-07-15 17:41 UTC, venturars commented on staff/vanessa-cardoso/challenges/challenge-is-even.js
> +let result1 = isEven(1)
Mejor utilizar const porque el valor no puede mutar

2024-07-15 17:45 UTC, venturars commented on staff/vanessa-cardoso/challenges/challenge-is-even.js
> +let result2 = isEven(2)
Por favor, incluye solo los test marcados en clase

2024-07-17 10:52 UTC, rucev approved these changes
code works fine 👍

2024-07-17 11:27 UTC, LeideVanessaC commented on staff/vanessa-cardoso/challenges/challenge-is-even.js
> +let result2 = isEven(2)
Ya corregí el código y so lo deje o que habías pasado en clase.

2024-07-17 11:27 UTC, LeideVanessaC commented on staff/vanessa-cardoso/challenges/challenge-is-even.js
> +let result1 = isEven(1)
ya cambié las variables para const.

2024-07-17 13:35 UTC, CarlosLemonCode approved these changes
Aprobada! =D

2024-07-17 16:56 UTC, CRBM84 approved these changes

2024-07-17 17:54 UTC, merged