#83-challenge-is-even
b00tc4mp/isdi-parttime-202406 pull request #84
Opened 2024-07-08 17:32 UTC by itsmePo

Challenge is even

2024-07-08 17:42 UTC, Carlos00004 commented
Recuerda que estamos testeando si es número par o no en caso de los **_números_**, y si es par o no en caso del _**número de carácteres**_  que contienen las strings!

2024-07-08 17:43 UTC, Carlos00004 requested changes
Échale un ojo a las reviews 👍 :)

2024-07-08 17:43 UTC, Carlos00004 commented on staff/borja-garcia/challenges/challenge-is-even.js
> +        return false;
Todo lo que no es un número, lo declara como falso. No te corre el código con todo lo que no es un número!

2024-07-08 17:43 UTC, Carlos00004 commented on staff/borja-garcia/challenges/challenge-is-even.js
> +    console.assert(result4 === false, {result: result4, message: 'Test 4 no pasado'})
Si te fijas, declara como falso todo lo que no es un número. Como en este test requieres que el boolean sea _**false**_, no te salta la alerta. Prueba a ponerle _**true**_ y verás como sí te salta.

2024-07-08 17:52 UTC, Portaltocoding requested changes

2024-07-08 17:52 UTC, Portaltocoding commented on staff/borja-garcia/challenges/challenge-is-even.js
> +        return false;
ídem + la idea esta bien planteada la relación de if negativa; pero esta incompleta, aqui sí detecta tipo pero falta continuar con el conteo .

2024-07-08 17:52 UTC, Portaltocoding commented on staff/borja-garcia/README.md
Creo que esto es debido al pull que has hecho, poniendonos picky deberías haberlo hecho de forma separada como update y ahora al subir el challenge, esto aparte. Pero bueno que todo chachi y esto da igual 🍰 🍰

2024-07-08 17:55 UTC, CRBM84 reviewed
Tienes que modificar un poco para poder procesar strings.

2024-07-08 17:55 UTC, CRBM84 commented on staff/borja-garcia/challenges/challenge-is-even.js
> +        return false;
Puedes usar una condición de && para usar dos type of depende como quieras construir el código y la lógica.

2024-07-18 15:28 UTC, CarlosLemonCode commented
Recuerda poner el ID en los commits please 🤞

2024-07-18 15:34 UTC, CarlosLemonCode commented on staff/borja-garcia/challenges/challenge-is-even.js
El código funciona si testea una sola palabra. Si hay más de una, o hay algún espacio, considera el espacio como un carácter también. Te dejo una posible solución en caso de que quieras que descarte los espacios! 

```js
function isEven(value) {
        if (typeof value === "number") {
            return value % 2 === 0;
        } else if (typeof value === "string") {
            const noSpace = value.replace(/\s+/g, '')
            return noSpace.length % 2 === 0;
        } else {
            return false;
        }
    }
```

2024-07-18 15:36 UTC, CarlosLemonCode approved these changes

2024-07-18 16:49 UTC, itsmePo commented on staff/borja-garcia/challenges/challenge-is-even.js
Muchas gracias, man!
Ni lo había pensado, la verdad.
Voy a cambiar el archivo para dejarlo con la opción para espacios y, por fin, matar la PR.

2024-07-18 17:00 UTC, CRBM84 approved these changes
El código trabaja, por favor, usar const en el futuro en vez de let.

2024-07-18 17:04 UTC, Portaltocoding approved these changes

2024-07-22 11:04 UTC, rucev approved these changes

2024-07-22 11:04 UTC, merged