#85-is-even-challenge
b00tc4mp/isdi-parttime-202406 pull request #86
Opened 2024-07-08 17:46 UTC by Rodrigoregomedeiros

Challenge is Even

2024-07-08 17:58 UTC, CRBM84 commented on staff/rodrigo-medeiros/challenges/isEven.js
> +debugger
Flata el { en el debugger

2024-07-08 18:09 UTC, venturars requested changes
Ela rchivo 'staff/rodrigo-medeiros/challenges/binary-to-decimal.js' no debe estar en esta PR

2024-07-10 09:13 UTC, Rafa0297 requested changes
En el return debes cambiar el string por un booleano para que funcione el codigo

2024-07-10 11:26 UTC, Rafa0297 approved these changes
Funciona bien! 👍

2024-07-10 17:38 UTC, venturars requested changes
Revisa el nombre del archivo, esa no es la nomenclatura correcta

2024-07-10 17:41 UTC, CRBM84 approved these changes
👍🏼

2024-07-10 17:43 UTC, Rafa0297 approved these changes

2024-07-10 17:45 UTC, venturars approved these changes
Todo perfe

2024-07-10 17:45 UTC, merged