88 challenge binary to decimal
b00tc4mp/isdi-parttime-202406 pull request #89
Opened 2024-07-10 13:02 UTC by itsmePo

2024-07-10 14:55 UTC, Rafa0297 commented
El codigo va bien pero deberias guardar el archivo en una carpeta que se llame `staff/borja-garcia/challenges` y tu rama deberia apuntar a develop y no a main

2024-07-10 14:56 UTC, Rafa0297 requested changes
Debes guardar el archivo en la carpeta challenges y cambiar hacia donde apunta la rama

2024-07-10 15:42 UTC, Portaltocoding requested changes
Po! Ojo con lo de la rama Main! es un fallo tonto pero así no te lo podemos aprobar 😢 ! tema aparte según el estilo el título es incorrecto! 👨‍💻 🌵

2024-07-10 17:34 UTC, venturars commented
Todo bien pero los siguientes commits porfi mételes el número de la issue

2024-07-10 17:41 UTC, venturars approved these changes
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2024-07-10 17:41 UTC, merged

2024-07-11 05:51 UTC, CRBM84 reviewed
Nice work :)